### PR TITLE
Added a browser platform support 

### PR DESCRIPTION
**Pull request by klirix**

### CODE REVIEW

**Comment by ihadeed** [comment]
Thanks @klirix 

Looks great, and I like the idea of automatically injecting the stripe js, very convenient!

There are only styling issues with this PR, but I will fix that after merging. Just missing spacing and semi-colons.

**Comment by jacquesdev** [comment]
Hello - can someone please tell me how this works, because if Stripe.js gets injected automatically, I would expect to access a object called Stripe, since cordova.plugins.stripe.createCardToken would not work in the browser (cordova is undefined in the browser).

So please advise how I should be calling this in the browser because I am not sure how to do that, and I don't see Stripe?

**Comment by ihadeed** [comment]
@jacquesdev 

It should show up if you run `cordova run browser` or `cordova build browser`. 

I think this automatic injection feature should be removed, to avoid situations like this where you want to run the app in the browser without the Cordova Browser platform (e.g. `ionic serve`).

**Comment by jacquesdev** [comment]
Ah ok, I did not even realise there is an option like that. I am happy to leave it in - will try and run the app like this. Much easier for testing

**Comment by mariohmol** [comment]
Hi there!! Awesome news about using in web as well.. is it possible to run as a normal html app or just works if i can via `cordova run browser` ?

Cause when i try to run in a express static for instance, I got this message `Native: tried calling Stripe.setPublishableKey, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator`.

As this is running on web not using cordova.js at all a neither in a emulator (in a browser instead)

**Comment by ihadeed** [comment]
@mariohmol  It only works via `cordova run browser`

Please open a new issue for any further questions.

**Pull request merged**
